//LOCAL SERVER
###
GET http://localhost:3000/quotes

###
POST http://localhost:3000/quotes
Content-Type: application/json

{

}

###
GET http://localhost:3000/quotes/6334ba162c2da193feea33ed




//RENDER

###
GET https://quotes-app-7pqb.onrender.com/quotes

###
POST https://quotes-app-7pqb.onrender.com/quotes
Content-Type: application/json

{

}


###
GET https://quotes-app-7pqb.onrender.com/quotes/6334ba162c2da193feea33ed